esphome:
  name: "mcp3421_pH_sensor"
  platform: ESP32
  board: esp32-devkit-v1

external_components:
  - source:
      type: git
      url: https://github.com/your-username/your-repo-name
      ref: main

sensor:
  - platform: mcp3421
    name: "pH Sensor"
    id: ph_sensor
    update_interval: 10s
